In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# read in original data
data = pd.read_csv("ungroupedLabData_train.csv")

In [66]:
set(data["label1"])

{'% hemoglobin a1c Blood',
 'absolute basophil count Blood',
 'absolute eosinophil count Blood',
 'absolute lymphocyte count Blood',
 'absolute monocyte count Blood',
 'absolute neutrophil count Blood',
 'alanine aminotransferase (alt) Blood',
 'albumin Blood',
 'albumin urine Urine',
 'albumin/creatinine urine Urine',
 'alkaline phosphatase Blood',
 'alveolar-arterial gradient Blood',
 'ammonia Blood',
 'amorphous crystals Urine',
 'amylase Blood',
 'anion gap Blood',
 'anisocytosis Blood',
 'anti-nuclear antibody Blood',
 'anticardiolipin antibody igg Blood',
 'anticardiolipin antibody igm Blood',
 'arch-1 Blood',
 'asparate aminotransferase (ast) Blood',
 'atypical lymphocytes Blood',
 'bacteria Urine',
 'bands Blood',
 'base excess Blood',
 'basophils Blood',
 'bicarbonate Blood',
 'bicarbonate urine Urine',
 'bilirubin Urine',
 'bilirubin direct Blood',
 'bilirubin indirect Blood',
 'bilirubin total Blood',
 'bite cells Blood',
 'blood Urine',
 'c-reactive protein Blood',
 'calcium oxalate crystals Urine',
 'calcium total Blood',
 'calcium urine Urine',
 'calculated bicarbonate whole blood Blood',
 'calculated tbg Blood',
 'calculated thyroxine (t4) index Blood',
 'calculated total co2 Blood',
 'carboxyhemoglobin Blood',
 'cellular cast Urine',
 'chloride Blood',
 'chloride urine Urine',
 'chloride whole blood Blood',
 'cholesterol hdl Blood',
 'cholesterol ldl calculated Blood',
 'cholesterol ratio (total/hdl) Blood',
 'cholesterol total Blood',
 'ck-mb index Blood',
 'cortisol Blood',
 'creatine kinase (ck) Blood',
 'creatine kinase mb isoenzyme Blood',
 'creatinine Blood',
 'creatinine urine Urine',
 'cyclosporin Blood',
 'digoxin Blood',
 'double stranded dna Blood',
 'eag Blood',
 'echinocytes Blood',
 'eosinophils Ascites',
 'eosinophils Blood',
 'eosinophils Urine',
 'epithelial cells Urine',
 'estimated gfr (mdrd equation) Blood',
 'ferritin Blood',
 'fibrinogen functional Blood',
 'folate Blood',
 'free calcium Blood',
 'free kappa Blood',
 'free kappa/free lambda ratio Blood',
 'free lambda Blood',
 'gentamicin Blood',
 'globulin Blood',
 'glucose Blood',
 'glucose Urine',
 'glucose pleural Pleural',
 'granular casts Urine',
 'h Blood',
 'haptoglobin Blood',
 'hematocrit Blood',
 'hematocrit calculated Blood',
 'hemoglobin Blood',
 'hepatitis a virus antibody Blood',
 'hepatitis b surface antibody Blood',
 'hepatitis b surface antigen Blood',
 'hepatitis b virus core antibody Blood',
 'hepatitis c virus antibody Blood',
 'hiv screen Blood',
 'hpe1 Blood',
 'hpe2 Blood',
 'hpe3 Blood',
 'hpe7 Blood',
 'hyaline casts Urine',
 'hypochromia Blood',
 'i Blood',
 'immature granulocytes Blood',
 'inpatient hematology/oncology smear Blood',
 'inr(pt) Blood',
 'iron Blood',
 'iron binding capacity total Blood',
 'joint crystals birefringence Joint Fluid',
 'joint crystals comment Joint Fluid',
 'joint crystals location Joint Fluid',
 'joint crystals number Joint Fluid',
 'joint crystals shape Joint Fluid',
 'ketone Urine',
 'l Blood',
 'lactate Blood',
 'lactate dehydrogenase (ld) Blood',
 'lactate dehydrogenase pleural Pleural',
 'large platelets Blood',
 'length of urine collection Urine',
 'leukocytes Urine',
 'lipase Blood',
 'lithium Blood',
 'luc Blood',
 'lymphocytes Ascites',
 'lymphocytes Blood',
 'lymphocytes Joint Fluid',
 'lymphocytes Other Body Fluid',
 'macrocytes Blood',
 'macrophage Other Body Fluid',
 'magnesium Blood',
 'magnesium urine Urine',
 'mch Blood',
 'mchc Blood',
 'mcv Blood',
 'mesothelial cell Ascites',
 'metamyelocytes Blood',
 'methemoglobin Blood',
 'microcytes Blood',
 'monocytes Ascites',
 'monocytes Blood',
 'monocytes Joint Fluid',
 'monos Other Body Fluid',
 'myelocytes Blood',
 'neutrophils Blood',
 'nitrite Urine',
 'ntprobnp Blood',
 'nucleated red cells Blood',
 'o2 flow Blood',
 'osmolality measured Blood',
 'osmolality urine Urine',
 'other Ascites',
 'other cells Blood',
 'ovalocytes Blood',
 'oxygen Blood',
 'oxygen saturation Blood',
 'pappenheimer bodies Blood',
 'parathyroid hormone Blood',
 'pco2 Blood',
 'pencil cells Blood',
 'ph Blood',
 'ph Urine',
 'phenytoin Blood',
 'phosphate Blood',
 'phosphate urine Urine',
 'platelet clumps Blood',
 'platelet count Blood',
 'platelet smear Blood',
 'po2 Blood',
 'poikilocytosis Blood',
 'polychromasia Blood',
 'polys Ascites',
 'polys Joint Fluid',
 'polys Other Body Fluid',
 'potassium Blood',
 'potassium urine Urine',
 'potassium whole blood Blood',
 'prostate specific antigen Blood',
 'protein Urine',
 'protein total Blood',
 'protein/creatinine ratio Urine',
 'pt Blood',
 'ptt Blood',
 'rbc Urine',
 'rbc ascites Ascites',
 'rbc clumps Urine',
 'rbc joint fluid Joint Fluid',
 'rbc other fluid Other Body Fluid',
 'rdw Blood',
 'rdw-sd Blood',
 'red blood cells Blood',
 'renal epithelial cells Urine',
 'required o2 Blood',
 'reticulocyte count automated Blood',
 'rheumatoid factor Blood',
 'schistocytes Blood',
 'sedimentation rate Blood',
 'sodium Blood',
 'sodium urine Urine',
 'sodium whole blood Blood',
 'specific gravity Urine',
 'sperm Urine',
 'teardrop cells Blood',
 'temperature Blood',
 'thyroid stimulating hormone Blood',
 'thyroxine (t4) Blood',
 'thyroxine (t4) free Blood',
 'total nucleated cells ascites Ascites',
 'total nucleated cells joint Joint Fluid',
 'total nucleated cells other Other Body Fluid',
 'total protein pleural Pleural',
 'total protein urine Urine',
 'transferrin Blood',
 'transitional epithelial cells Urine',
 'triglycerides Blood',
 'triiodothyronine (t3) Blood',
 'troponin t Blood',
 'uhold Urine',
 'uptake ratio Blood',
 'urea nitrogen Blood',
 'urea nitrogen urine Urine',
 'uric acid Blood',
 'uric acid crystals Urine',
 'uric acid urine Urine',
 'urine appearance Urine',
 'urine color Urine',
 'urine mucous Urine',
 'urobilinogen Urine',
 'vancomycin Blood',
 'vitamin b12 Blood',
 'wbc Urine',
 'wbc clumps Urine',
 'white blood cells Blood',
 'yeast Urine'}

In [96]:
labLabels = {"hemoglobin":"CBC", "hematocrit":"CBC","nucleated red cells":"CBC", "blood cells":"CBC" , "mch":"CBC", "mcv":"CBC", "platelet":"CBC", "rdw":"CBC", "rbc":"CBC", "wbc":"CBC",'poikilocytosis':"CBC", 'hypochromia':"CBC", "microcytes":"CBC", 'polychromasia':"CBC", 'anisocytosis':"CBC", 'macrocytes':"CBC", "monocyte":"CBC",
              "neutrophil":"CBC",   "eosinophil":"CBC", "basophil" :"CBC",
             "o2":"ABG", "base excess":"ABG", "oxygen":"ABG","alveolar-arterial":"ABG",
                 "calcium":"calcium",
                 "potassium":"Electrolytes", "chloride":"Electrolytes", "sodium":"Electrolytes", "bicarbonate":"Electrolytes","phosphate":"Electrolytes","magnesium":"Electrolytes",
                 "cholesterol":"cholesterol",
                 "glucose":"glucose",
                 "hepatitis":"hepatitis", "hiv":"HIV",
                 "bilirubin":"Bilirubin",
                 "ptt":"pt", "inr(pt)":"pt",
                 "aminotransferase":"aminotransferase",
                 "lactate":"lactate",
                 "lymph":"leukocytes", "eosinophils":"leukocytes", "monocytes":"leukocytes", "neutrophils":"leukocytes","basophils":"leukocytes", "granulocytes":"leukocytes", "metamyelocytes":"leukocytes", "myelocytes":"leukocytes",
                 "amylase":"pancreas", "lipase":"pancreas",
                 "creatine kinase":"creatine kinase", "ck-mb":"creatine kinase"
                }
labremove = ["top hold","bands","urine tube held","ventilat","waxy casts","edta hold" ,"peep","specimen","intubated","assist","tidal volume","tacrofk"]

In [84]:
# remove infrequent events
data["label1"].value_counts()["glucose Blood"]

10185

In [85]:
events = list(set(data["label1"]))

In [98]:
groupdic = {}
for e in events:
    print
    lowe = e.lower()
    if e in ["h Blood","i Blood","l Blood","bands Blood","sw  ","ns"] or lowe in labremove: continue
    
    if e == "ph Blood": 
        groupdic[e] = "ABG"
        continue
    if e == "pt Blood":
        groupdic[e] = "pt"
        continue
    
    if "Urine" in e: 
        groupdic[e] = "Urinalysis"
        continue
    if "Pleural" in e:
        groupdic[e] = "Pleural"
        continue
    if "Fluid"in e:
        groupdic[e] = "Fluid"
        continue
    if "Ascites" in e:
        groupdic[e] = "Ascites"
        continue
        
    for item in labLabels.keys():
        if item in lowe:
            groupdic[e] = labLabels[item]
            continue
    #print("here, ", e)
    if e not in groupdic.keys() and data["label1"].value_counts()[e] > 20:
        print(e)
        groupdic[e] = e

eag Blood
estimated gfr (mdrd equation) Blood
vancomycin Blood
thyroid stimulating hormone Blood
troponin t Blood
albumin Blood
alkaline phosphatase Blood
urea nitrogen Blood
creatinine Blood
temperature Blood
fibrinogen functional Blood
anion gap Blood

In [77]:
groupdic["digoxin Blood"]

'digoxin Blood'

In [99]:
set(groupdic.values())

{'ABG',
 'Ascites',
 'Bilirubin',
 'CBC',
 'Electrolytes',
 'Fluid',
 'HIV',
 'Pleural',
 'Urinalysis',
 'albumin Blood',
 'alkaline phosphatase Blood',
 'aminotransferase',
 'anion gap Blood',
 'calcium',
 'cholesterol',
 'creatine kinase',
 'creatinine Blood',
 'eag Blood',
 'estimated gfr (mdrd equation) Blood',
 'fibrinogen functional Blood',
 'glucose',
 'hepatitis',
 'lactate',
 'leukocytes',
 'pancreas',
 'pt',
 'temperature Blood',
 'thyroid stimulating hormone Blood',
 'troponin t Blood',
 'urea nitrogen Blood',
 'vancomycin Blood'}

In [107]:
num = {}
i= 1
for item in set(groupdic.values()):
    num[item] = i
    i+=1

In [109]:
group = []
for item in list(set(data["label1"])):
    if item in groupdic.keys():
        group.append([item, num[groupdic[item]]])
    else:
        group.append([item, 0])

In [112]:
df = pd.DataFrame(group, columns=["event", "group"])
df

                             event  group
0                 myelocytes Blood     11
1             platelet count Blood     31
2          glucose pleural Pleural      3
3                  phenytoin Blood      0
4                   globulin Blood      0
..                             ...    ...
225            eosinophils Ascites     22
226  absolute basophil count Blood     31
227                  protein Urine      7
228                  inr(pt) Blood      6
229                magnesium Blood     20

[230 rows x 2 columns]

In [115]:
df[df["group"]==0]

                                         event  group
3                              phenytoin Blood      0
4                               globulin Blood      0
13   inpatient hematology/oncology smear Blood      0
14                                  iron Blood      0
16                        teardrop cells Blood      0
20                                     l Blood      0
28                            free kappa Blood      0
35                        thyroxine (t4) Blood      0
39                    sedimentation rate Blood      0
46                                     h Blood      0
47                              ntprobnp Blood      0
51                             uric acid Blood      0
52                           other cells Blood      0
53                    c-reactive protein Blood      0
58                            bite cells Blood      0
59           iron binding capacity total Blood      0
67                           free lambda Blood      0
68                           cyclosporin Blood      0
70                                     i Blood      0
76                            ovalocytes Blood      0
79                   double stranded dna Blood      0
80                                  hpe2 Blood      0
89                           transferrin Blood      0
96                   thyroxine (t4) free Blood      0
99          reticulocyte count automated Blood      0
103                  pappenheimer bodies Blood      0
106                          haptoglobin Blood      0
107                          echinocytes Blood      0
109                        triglycerides Blood      0
112         free kappa/free lambda ratio Blood      0
113         anticardiolipin antibody igg Blood      0
120                                bands Blood      0
122                             ferritin Blood      0
125                                  luc Blood      0
126      calculated thyroxine (t4) index Blood      0
127            prostate specific antigen Blood      0
138                              lithium Blood      0
145                        protein total Blood      0
153                              ammonia Blood      0
154                         uptake ratio Blood      0
162                       calculated tbg Blood      0
165                               arch-1 Blood      0
169                  parathyroid hormone Blood      0
174                             cortisol Blood      0
178                         schistocytes Blood      0
179                           gentamicin Blood      0
180                anti-nuclear antibody Blood      0
181                                 hpe3 Blood      0
185                         pencil cells Blood      0
186         anticardiolipin antibody igm Blood      0
187                triiodothyronine (t3) Blood      0
196                  osmolality measured Blood      0
199                                 hpe7 Blood      0
204                    rheumatoid factor Blood      0
206                          vitamin b12 Blood      0
210                               folate Blood      0
219                                 hpe1 Blood      0
220                              digoxin Blood      0

In [113]:
df.to_csv("expert.csv",index=False)

In [26]:
len(set(groupdic.values()))

16

In [41]:
# apply dictionary
newlist = data[data["label1"].isin(groupdic.keys())]
newlist = newlist.replace(groupdic)

In [42]:
newlist

,hadm_id,charttime,label,fluid,admittime,label1
0,28737610,2154-03-27 12:22:00,ph,Blood,2154-03-27 07:45:00,ABG
1,22325703,2180-03-28 15:07:00,free calcium,Blood,2180-03-28 07:15:00,calcium
2,20468701,2116-11-06 15:13:00,free calcium,Blood,2116-11-06 07:45:00,calcium
3,20468701,2116-11-09 04:56:00,absolute basophil count,Blood,2116-11-06 07:45:00,ABG
4,28487115,2170-02-07 07:35:00,calculated total co2,Blood,2170-02-07 07:15:00,ABG
...,...,...,...,...,...,...
188020,28754414,2185-08-27 13:26:00,red blood cells,Blood,2185-08-27 15:30:00,CBC
188021,20319352,2145-04-16 02:20:00,red blood cells,Blood,2145-04-14 07:15:00,CBC
188022,24041084,2139-08-14 04:53:00,red blood cells,Blood,2139-08-13 07:45:00,CBC
188023,24483986,2194-08-09 14:22:00,red blood cells,Blood,2194-08-09 07:15:00,CBC
188024,20255209,2123-05-10 03:07:00,red blood cells,Blood,2123-05-09 07:15:00,CBC

In [43]:
newlist.to_csv('expertgroupdata.csv', index=False)

In [45]:
newlist1 = []
for key, value in groupdic.items():
    newlist1.append([value, key])

In [48]:
newlist1 = pd.DataFrame(newlist1)

In [49]:
newlist1.to_csv('expertgroups.csv', index=False)